### ISSUE TITLE
CoroUtils config logic - please add only overworld AND tropicraft

### ISSUE THREAD

**Issue by ProsperCraft** [Corosauce/CoroUtil#10]
I have a modpack with over 50 dims and the memory issue was hitting us hard till I changed the config to overworld only, but now I get this console spam when people are in the tropics- 

http://pastebin.com/H4SFt5Bu

Are you able to change your config logic to be overworld and tropics only?

or change the config to be where we can whitelist dims instead of having to go through and blacklist every dim?

**Comment by Bogdan-G** [comment]
mm! NPE, more NPE!

**Comment by Corosauce** [comment]
Added ability to use the blacklist ID / name feature as a whitelist instead, should help with modpacks that have more dynamic dimensions than static ones you don't want touched by PFQueue https://github.com/Corosauce/CoroUtil/commit/f38849dc784b855b4990517ece31bdb9ef699284
