### ISSUE TITLE
Spam Log and drop fps

### ISSUE THREAD

**Issue by Bogdan-G** [Corosauce/CoroUtil#11]
Hello. 
Java 8_66, MC 1.7.10, Forge 1614, FC ctest17, no Optifine, SSP and SMP(and Vanilla Forge and KCauldron)
Version of the mod 1.1.3
mod list: http://imgur.com/pZS52Re
config in git: https://github.com/Bogdan-G/Burner-ModPack-Lite/tree/master/build/config
If enable options: B:chunkCacheOverworldOnly=true
in neighboring issue that helped to reduce the amount of memory usage, when so many worlds, I have them 41. In the log there is a cyclical incessant spam(game pause not stop spam):
https://gist.github.com/Bogdan-G/a265bb5d08e06769da48

over time, the log file size is significantly increased, since it takes a few minutes (beginning spam) after creation. And in sync with the FPS dropped to 1 and jVisualVM Garbage collection shows the constant and very small size of Eden, evidently at every NPE throwing garbage collection occurs:
http://imgur.com/93J4opD | http://imgur.com/ICoroJ0 (while I was writing, I saw what the screenshots before the text was dial 28K assemblies)
just by holding the client in this mode increases the number of assemblies in the old generation and the number of unloaded classes.
P.S. At the same time that I wrote above, the cursor disappears somewhere in the game.

fml-lastest-log + latest.log + gc.log: https://yadi.sk/d/hlxU-w7vmi5iw

**Comment by Bogdan-G** [comment]
Problem not solved, gg))
PS JVM version has no effect

**Comment by Corosauce** [comment]
Added ability to use the blacklist ID / name feature as a whitelist instead, should help with modpacks that have more dynamic dimensions than static ones you don't want touched by PFQueue https://github.com/Corosauce/CoroUtil/commit/f38849dc784b855b4990517ece31bdb9ef699284

Additionally I think I will by default surpress these NPEs as they are not critical crashing issues, just more of a design flaw.

**Comment by Corosauce** [comment]
https://github.com/Corosauce/CoroUtil/commit/6cf04194b73e77906f5eff22bf948a8a0ca83e57

**Comment by Bogdan-G** [comment]
ok, thx, I'm going to test it
