### ISSUE TITLE
Possible crash when cleaning up stray mobs

### ISSUE THREAD

**Issue by TheAzack9** [Corosauce/CoroUtil#15]
I'm not sure if this is the right place to post this so just remove it if this is the wrong place :)

Note: this is on a server :)
Not at all a modder, but i can code so i did some digging on a crash i had. I am not the expert here, but i figured out from some searching that this might be the culprit: https://github.com/Corosauce/CoroUtil/blob/0547963ad61a0bf6412c3d35da79125e2a8ac291/src/main/java/CoroUtil/world/player/DynamicDifficulty.java#L70

It seems that this function is trying to call client side code, but i might be wrong about that ;)
Comment from LexManos: http://www.minecraftforge.net/forum/topic/22229-server-crash-when-calling-worldgetloadedentitylist/?do=findComment&comment=114656

Attached crash log:
[crash-2017-04-09_12.25.34-server.txt](https://github.com/Corosauce/CoroUtil/files/908132/crash-2017-04-09_12.25.34-server.txt)

This might very well be a compability issue with mods. I honestly have no clue about that. 
It stopped crashing when setting "B:cleanupStrayMobs" to false, which in the code will stop the code in question of running.

**Comment by Corosauce** [comment]
Hah, that used to work, it must have gotten remarked with a side only since the feature was added, thankfully world.loadedEntityList is public anyways so I'll just use that, will be fixed for next CoroUtil release.
