### ISSUE TITLE
Update To Forge 2555 (1.12.2)

### ISSUE THREAD

**Issue by kenijey** [Corosauce/CoroUtil#20]
Can you update your Forge to 2555(1.12.2) please? For CoroUtil and Weather. Thanks.

**Comment by Corosauce** [comment]
Why? did something break?

**Comment by kenijey** [comment]
no i just saw theres a bit many changes between xD but all as you wish

**Comment by Corosauce** [comment]
You should be able to use newer forge just fine with my stuff, not that i've tested, they maintain backwards compatibility within same mc versions.

**Comment by Divineaspect** [comment]
The problem atm is Immersive Engineering isn't compatible past 2555, not really your problem.

**Comment by Corosauce** [comment]
Cool, I guess ill close this, if anyone experiences any issues using a newer forge with my stuff, that would be definitely worthy of an issue report.

**Comment by kenijey** [comment]
yeah, im sorry about disturbing..
