### ISSUE TITLE
[1.7.10] Server Crash - java.lang.NoSuchMethodError: CoroUtil.world.WorldDirector.addTickingLocation(LCoroUtil/world/location/ManagedLocation;)V

### ISSUE THREAD

**Issue by ProsperCraft** [Corosauce/CoroUtil#23]
https://paste.fedoraproject.org/paste/awZ9w4nA~OMo3x7NiayuUA

Modpack - https://minecraft.curseforge.com/projects/drtardis-adventure-modpack

**Comment by ProsperCraft** [comment]
The server keeps crashing every time a certain player joins.

https://paste.fedoraproject.org/paste/8DpfvWgi49sm1Gb8JHz4wA

**Comment by Corosauce** [comment]
Paste links invalid, 1.7.10 not supported anymore anyways.

**Comment by ProsperCraft** [comment]
Please revisit this and fix this error, it is the only crash we get, and all of the players start in the tropics in my pack.

https://gist.github.com/ProsperCraft/640213ceeff6ef0843d646da83ddc5df
