### ISSUE TITLE
Crash on Server with CoroUtil 1.2.4 (!)

### ISSUE THREAD

**Issue by D3nnis3n** [Corosauce/CoroUtil#25]
See this Crash-Report: https://gist.github.com/D3nnis3n/c077131ab29a58560e0a11e036fc4313

**Comment by Corosauce** [comment]
Thanks, fixed, gonna push a new build in a bit. https://github.com/Corosauce/weather2/commit/c5be08563eb73b6e6fd353ef4927b24d72e270ab
