### ISSUE TITLE
Pam's HarvestCraft Glitch

### ISSUE THREAD

**Issue by Presistedcrib** [Corosauce/CoroUtil#35]
Unable to give the PlayerZombie raw meat to calm them down when Pam's Harvestcraft is installed.

Maybe an issue with the foods added by Pam's that makes it not detect ANY food properly? Idk

**Comment by Corosauce** [comment]
In Zombie_Players.cfg enable enableAdvancedDeveloperConfigFiles, then once Zombie_Players_Advanced.cfg exists, add pams raw meats to calmingItems list, if all their raw meats have a specific ore dictionary name you can add just that instead.

I might move this setting to the main config file in the future for easier changing.
