### ISSUE TITLE
Crash when invasion starts

### ISSUE THREAD

**Issue by ghost** [Corosauce/CoroUtil#36]
When the invasion starts up and the first mob spawns it crashes.
(My guess is that dynamic stealth's AI conflicts with the one in the invasion mod)
[Vanilafix Link](https://paste.dimdev.org/ijokijexun.mccrash)
[crash-2019-05-20_09.33.31-server.txt](https://github.com/Corosauce/CoroUtil/files/3198760/crash-2019-05-20_09.33.31-server.txt)

**Comment by Corosauce** [comment]
Yeah you're probably right, target overriding mods can break code flow expectations in AI tasks, I'll have to add more safety checks in my code to fix this.

**Comment by Corosauce** [comment]
Fixed https://github.com/Corosauce/CoroUtil/commit/6aae7ee8808fad30cf5759bc3b216448f91a56db, pushing out new CoroUtil build
