### ISSUE TITLE
massive log spam

### ISSUE THREAD

**Issue by mattrix444** [Corosauce/CoroUtil#37]
hi i seem to be getting tons of log spam over the last few days ([14:48:48] [Server thread/INFO] [STDOUT]: [CoroUtil.world.WorldDirector:removeTickingLocation:168]: Error, couldnt find location for removal) being spammed constantly until i quit the world i'm playing. im using 1.2.32 version for 1.12.2 thanks

**Comment by Corosauce** [comment]
:+1: https://github.com/Corosauce/CoroUtil/commit/458dc127b0de0ee33f7a6c097281c2b2ccce0ac4
