### ISSUE TITLE
 CoroUtil not compatible with spongeforge

### ISSUE THREAD

**Issue by Toto6LP** [Corosauce/CoroUtil#40]
Hi. Could you perhaps make an update because this mod does not work with Spongeforge. And that is very important. MC 1.12.2

forge-1.12.2-14.23.5.2838-universal

spongeforge-1.12.2-2838-7.1.7-RC3928

**Comment by Corosauce** [comment]
Define 'not compatible' ? not much info to go with here

**Comment by NLBlacky** [comment]
We've had CoroUtil with the following SpongeForge versions without any issues. You might want to post a crashlog and information about which modpack so I might be able to take a look for you as well.

**Confirmed working versions:**
> spongeforge-1.12.2-2838-7.2.0.jar (For Mixin 0.8 = newer packs / mod updates)
> spongeforge-1.12.2-2838-7.1.7-RC3924.jar (older Mixin, will work on most packs)
