### ISSUE TITLE
Invalid bounds generated for `Double` entries

### ISSUE THREAD

**Issue by endorh** [Corosauce/CoroUtil#55]
The `Double` config entries created by [`ModConfigData`](https://github.com/Corosauce/CoroUtil/blob/1.18/src/main/java/com/corosus/modconfig/ModConfigData.java) in [`ModConfigData#addToConfig`](https://github.com/Corosauce/CoroUtil/blob/a390fa823f082be3c2a9bc9a83aa6ae12c6af966/src/main/java/com/corosus/modconfig/ModConfigData.java#L273) do not allow the value of `0` nor any negative numbers.

I'll agree that whoever named the constants was kind of a jerk, but [`Double.MIN_VALUE`](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#MIN_VALUE) [isn't what you thought it was](https://stackoverflow.com/questions/3884793/why-is-double-min-value-in-not-negative) 😅, it's the smallest non-zero positive number representable as a `double`. What you want is probably [`Double.NEGATIVE_INFINITY`](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#NEGATIVE_INFINITY) or [`-Double.MAX_VALUE`](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#MAX_VALUE) instead (they're not the same either).

https://github.com/Corosauce/CoroUtil/blob/a390fa823f082be3c2a9bc9a83aa6ae12c6af966/src/main/java/com/corosus/modconfig/ModConfigData.java#L300

This recently blew up my own mod, Simple Config, when it attempted to wrap config files created by `CoroUtil`. I added a safeguard on my end to ignore invalid entry ranges, but I thought I'd also let you know of this small mistake. ^^

**Comment by Corosauce** [comment]
Oh TIL, good tip thanks!
