### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [Corosauce/CoroUtil#59]
MC 1.20.1
Neoforge

https://mclo.gs/07TPSIn

**Comment by Proxwian** [comment]
Same thing here

**Comment by Corosauce** [comment]
I briefly released a version of coroutil (coroutil-forge-1.20.1-1.3.5) that broke backwards compatibility, thought marking it alpha would prevent people from updating, I was wrong xD. The latest coroutil (coroutil-forge-1.20.1-1.3.6) shouldn't have this issue now.
