### ISSUE TITLE
Mod error?

### ISSUE THREAD

**Issue by takaqiao** [Corosauce/CoroUtil#6]
All coros mods are error in kcauldron How to fix it?
17:32:31 java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
17:32:31    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_21]
17:32:31    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_21]
17:32:31    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59) ~[ProxyInjector.class:1.7.10-1492.152]
17:32:31    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[FMLModContainer.class:1.7.10-1492.152]
17:32:31    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:31    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:31    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:31    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:31    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:31    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1492.152]
17:32:31    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1492.152]
17:32:31    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:31    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:31    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:31    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:31    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:31    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:31    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1492.152]
17:32:31    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:1.7.10-1492.152]
17:32:31    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:1.7.10-1492.152]
17:32:31    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) [FMLCommonHandler.class:1.7.10-1492.152]
17:32:32    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) [lt.class:?]
17:32:32    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
17:32:32    at java.lang.Thread.run(Unknown Source) [?:1.7.0_21]
17:32:32 Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
17:32:32    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    ... 31 more
17:32:32 Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
17:32:32    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1492.152-server.jar:1.7.10-1492.152]
17:32:32    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
17:32:32    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    ... 31 more
17:32:32 [SEVERE] Encountered an unexpected exception
17:32:32 cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
17:32:32    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544) ~[Loader.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:1.7.10-1492.152]
17:32:32    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) ~[lt.class:?]
17:32:32    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
17:32:32    at java.lang.Thread.run(Unknown Source) [?:1.7.0_21]
17:32:32 Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
17:32:32    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_21]
17:32:32    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_21]
17:32:32    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59) ~[ProxyInjector.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[FMLModContainer.class:1.7.10-1492.152]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:32    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:32    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) ~[Loader.class:1.7.10-1492.152]
17:32:32    ... 5 more
17:32:32 Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
17:32:32    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_21]
17:32:32    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_21]
17:32:32    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59) ~[ProxyInjector.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[FMLModContainer.class:1.7.10-1492.152]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:32    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:32    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) ~[Loader.class:1.7.10-1492.152]
17:32:32    ... 5 more
17:32:32 Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
17:32:32    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1492.152-server.jar:1.7.10-1492.152]
17:32:32    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
17:32:32    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_21]
17:32:32    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_21]
17:32:32    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59) ~[ProxyInjector.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[FMLModContainer.class:1.7.10-1492.152]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
17:32:32    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1492.152]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
17:32:32    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
17:32:32    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
17:32:32    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]

**Comment by Corosauce** [comment]
Whatever happened I likely fixed this by now, lots of dedicated server testing has been done since this post.
