### ISSUE TITLE
No raindrops

### ISSUE THREAD

**Issue by Anadarn** [Corosauce/CoroUtil#8]
Hi,

When I install the mod in 1.7.10, everything works fine except that I can't see any raindrop nor hear them when it rains. It works fine when I take the mod away and I've already looked into the settings and changed the rain or raindrop configuration but nothing has changed.

**Comment by Anadarn** [comment]
Dude?

**Comment by Corosauce** [comment]
Issue old for older version and precipitation has since been rewritten for mc 1.10 versions
